# RuboCop config file
# Configure cops
# https://github.com/bbatsov/rubocop
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/ruby-style-guide
#

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Workaround until https://github.com/bbatsov/rubocop/issues/3752 is resolved
Bundler/DuplicatedGem:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# Support ruby 1.8.7
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# The shebang stuff at the top triggers this
Style/LeadingCommentSpace:
  Exclude:
    - Puppetfile

Style/TrailingCommaInLiteral:
  Enabled: false
